package com.forextrader.core.model;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Represents a trading signal generated by a strategy.
 * Contains information about the recommended trading action.
 */
public class Signal {
    private final UUID id;
    private final String symbol;
    private final SignalType type;
    private final Instant timestamp;
    private final String strategyId;
    private BigDecimal price;
    private BigDecimal targetPrice;
    private BigDecimal stopLoss;
    private BigDecimal confidence;  // 0.0 to 1.0
    private String rationale;
    private Map<String, Object> additionalParams;
    
    /**
     * Signal types representing different trading actions.
     */
    public enum SignalType {
        BUY,
        SELL,
        CLOSE_BUY,
        CLOSE_SELL,
        HOLD,
        UNKNOWN
    }
    
    /**
     * Creates a new Signal instance with the essential parameters.
     * 
     * @param symbol the trading symbol
     * @param type the signal type
     * @param strategyId the ID of the strategy that generated this signal
     */
    public Signal(String symbol, SignalType type, String strategyId) {
        this.id = UUID.randomUUID();
        this.symbol = symbol;
        this.type = type;
        this.strategyId = strategyId;
        this.timestamp = Instant.now();
        this.additionalParams = new HashMap<>();
    }
    
    /**
     * Creates a new Signal instance with all parameters.
     * 
     * @param symbol the trading symbol
     * @param type the signal type
     * @param strategyId the ID of the strategy that generated this signal
     * @param price the price at which the signal was generated
     * @param targetPrice the target price for taking profit
     * @param stopLoss the price for stop loss
     * @param confidence the confidence level (0.0 to 1.0)
     * @param rationale the rationale/reasoning behind the signal
     */
    public Signal(String symbol, SignalType type, String strategyId,
                 BigDecimal price, BigDecimal targetPrice, BigDecimal stopLoss,
                 BigDecimal confidence, String rationale) {
        this.id = UUID.randomUUID();
        this.symbol = symbol;
        this.type = type;
        this.strategyId = strategyId;
        this.timestamp = Instant.now();
        this.price = price;
        this.targetPrice = targetPrice;
        this.stopLoss = stopLoss;
        this.confidence = confidence;
        this.rationale = rationale;
        this.additionalParams = new HashMap<>();
    }
    
    /**
     * Gets the unique identifier for this signal.
     * 
     * @return the signal ID
     */
    public UUID getId() {
        return id;
    }
    
    /**
     * Gets the trading symbol.
     * 
     * @return the symbol
     */
    public String getSymbol() {
        return symbol;
    }
    
    /**
     * Gets the signal type.
     * 
     * @return the signal type
     */
    public SignalType getType() {
        return type;
    }
    
    /**
     * Gets the timestamp when the signal was generated.
     * 
     * @return the timestamp
     */
    public Instant getTimestamp() {
        return timestamp;
    }
    
    /**
     * Gets the ID of the strategy that generated this signal.
     * 
     * @return the strategy ID
     */
    public String getStrategyId() {
        return strategyId;
    }
    
    /**
     * Gets the price at which the signal was generated.
     * 
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }
    
    /**
     * Sets the price at which the signal was generated.
     * 
     * @param price the price to set
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
    /**
     * Gets the target price for taking profit.
     * 
     * @return the target price
     */
    public BigDecimal getTargetPrice() {
        return targetPrice;
    }
    
    /**
     * Sets the target price for taking profit.
     * 
     * @param targetPrice the target price to set
     */
    public void setTargetPrice(BigDecimal targetPrice) {
        this.targetPrice = targetPrice;
    }
    
    /**
     * Gets the price for stop loss.
     * 
     * @return the stop loss price
     */
    public BigDecimal getStopLoss() {
        return stopLoss;
    }
    
    /**
     * Sets the price for stop loss.
     * 
     * @param stopLoss the stop loss price to set
     */
    public void setStopLoss(BigDecimal stopLoss) {
        this.stopLoss = stopLoss;
    }
    
    /**
     * Gets the confidence level of the signal.
     * 
     * @return the confidence level (0.0 to 1.0)
     */
    public BigDecimal getConfidence() {
        return confidence;
    }
    
    /**
     * Sets the confidence level of the signal.
     * 
     * @param confidence the confidence level to set (0.0 to 1.0)
     */
    public void setConfidence(BigDecimal confidence) {
        this.confidence = confidence;
    }
    
    /**
     * Gets the rationale behind the signal.
     * 
     * @return the rationale
     */
    public String getRationale() {
        return rationale;
    }
    
    /**
     * Sets the rationale behind the signal.
     * 
     * @param rationale the rationale to set
     */
    public void setRationale(String rationale) {
        this.rationale = rationale;
    }
    
    /**
     * Adds an additional parameter to the signal.
     * 
     * @param key the parameter key
     * @param value the parameter value
     */
    public void addParameter(String key, Object value) {
        additionalParams.put(key, value);
    }
    
    /**
     * Gets an additional parameter value.
     * 
     * @param key the parameter key
     * @return the parameter value
     */
    public Object getParameter(String key) {
        return additionalParams.get(key);
    }
    
    /**
     * Gets all additional parameters.
     * 
     * @return the map of additional parameters
     */
    public Map<String, Object> getAllParameters() {
        return additionalParams;
    }
    
    /**
     * Checks if this signal is actionable (BUY, SELL, CLOSE_BUY, or CLOSE_SELL).
     * 
     * @return true if the signal is actionable, false otherwise
     */
    public boolean isActionable() {
        return type == SignalType.BUY || type == SignalType.SELL ||
               type == SignalType.CLOSE_BUY || type == SignalType.CLOSE_SELL;
    }
    
    @Override
    public String toString() {
        return String.format("Signal[id=%s, symbol=%s, type=%s, strategy=%s, confidence=%s]",
                            id, symbol, type, strategyId, confidence);
    }
} 