package com.forextrader.core.signal;

import com.forextrader.core.model.Signal;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;
import java.util.logging.Logger;

/**
 * Processes trading signals generated by strategies.
 * Applies filters, validations, and routes signals to appropriate handlers.
 */
public class SignalProcessor {
    private static final Logger logger = Logger.getLogger(SignalProcessor.class.getName());
    
    private final List<SignalFilter> filters = new ArrayList<>();
    private final List<SignalValidator> validators = new ArrayList<>();
    private final List<SignalHandler> handlers = new CopyOnWriteArrayList<>();
    private final List<Signal> recentSignals = new CopyOnWriteArrayList<>();
    
    private int maxRecentSignals = 100;
    private Duration signalTimeout = Duration.ofMinutes(5);
    private BigDecimal minimumConfidence = new BigDecimal("0.5");
    
    /**
     * Interface for signal filtering.
     */
    public interface SignalFilter {
        /**
         * Decides whether a signal should be processed further.
         * 
         * @param signal The signal to filter
         * @return true if the signal should be processed, false if it should be filtered out
         */
        boolean accept(Signal signal);
    }
    
    /**
     * Interface for signal validation.
     */
    public interface SignalValidator {
        /**
         * Validates a signal.
         * 
         * @param signal The signal to validate
         * @return A validation result
         */
        ValidationResult validate(Signal signal);
    }
    
    /**
     * Interface for handling signals.
     */
    public interface SignalHandler {
        /**
         * Handles a signal.
         * 
         * @param signal The signal to handle
         */
        void handleSignal(Signal signal);
    }
    
    /**
     * Validation result for signal validation.
     */
    public static class ValidationResult {
        private final boolean valid;
        private final String message;
        
        private ValidationResult(boolean valid, String message) {
            this.valid = valid;
            this.message = message;
        }
        
        /**
         * Creates a successful validation result.
         * 
         * @return A successful validation result
         */
        public static ValidationResult success() {
            return new ValidationResult(true, null);
        }
        
        /**
         * Creates a failed validation result with the specified message.
         * 
         * @param message The failure message
         * @return A failed validation result
         */
        public static ValidationResult failure(String message) {
            return new ValidationResult(false, message);
        }
        
        /**
         * Gets whether the validation was successful.
         * 
         * @return true if the validation was successful, false otherwise
         */
        public boolean isValid() {
            return valid;
        }
        
        /**
         * Gets the validation message.
         * 
         * @return The validation message, or null if there is no message
         */
        public String getMessage() {
            return message;
        }
    }
    
    /**
     * Creates a new signal processor with default filters and validators.
     */
    public SignalProcessor() {
        setupDefaultFilters();
        setupDefaultValidators();
    }
    
    /**
     * Sets up the default signal filters.
     */
    private void setupDefaultFilters() {
        // Filter out signals with insufficient confidence
        addFilter(signal -> {
            if (signal.getConfidence() == null) return true;
            return signal.getConfidence().compareTo(minimumConfidence) >= 0;
        });
        
        // Filter out non-actionable signals
        addFilter(Signal::isActionable);
        
        // Filter out expired signals
        addFilter(signal -> {
            Instant now = Instant.now();
            Instant signalTime = signal.getTimestamp();
            return Duration.between(signalTime, now).compareTo(signalTimeout) <= 0;
        });
    }
    
    /**
     * Sets up the default signal validators.
     */
    private void setupDefaultValidators() {
        // Validate that the signal has a symbol
        addValidator(signal -> {
            if (signal.getSymbol() == null || signal.getSymbol().trim().isEmpty()) {
                return ValidationResult.failure("Signal has no symbol");
            }
            return ValidationResult.success();
        });
        
        // Validate that the signal has a strategy ID
        addValidator(signal -> {
            if (signal.getStrategyId() == null || signal.getStrategyId().trim().isEmpty()) {
                return ValidationResult.failure("Signal has no strategy ID");
            }
            return ValidationResult.success();
        });
        
        // Validate that the signal has a price
        addValidator(signal -> {
            if (signal.getPrice() == null) {
                return ValidationResult.failure("Signal has no price");
            }
            return ValidationResult.success();
        });
    }
    
    /**
     * Adds a signal filter.
     * 
     * @param filter The filter to add
     */
    public void addFilter(SignalFilter filter) {
        filters.add(filter);
    }
    
    /**
     * Adds a signal validator.
     * 
     * @param validator The validator to add
     */
    public void addValidator(SignalValidator validator) {
        validators.add(validator);
    }
    
    /**
     * Adds a signal handler.
     * 
     * @param handler The handler to add
     */
    public void addHandler(SignalHandler handler) {
        handlers.add(handler);
    }
    
    /**
     * Removes a signal handler.
     * 
     * @param handler The handler to remove
     * @return true if the handler was removed, false if it was not found
     */
    public boolean removeHandler(SignalHandler handler) {
        return handlers.remove(handler);
    }
    
    /**
     * Processes a signal.
     * 
     * @param signal The signal to process
     * @return true if the signal was processed, false if it was filtered out or invalid
     */
    public boolean processSignal(Signal signal) {
        if (signal == null) {
            logger.warning("Received null signal");
            return false;
        }
        
        logger.info("Processing signal: " + signal);
        
        // Apply filters
        for (SignalFilter filter : filters) {
            if (!filter.accept(signal)) {
                logger.info("Signal filtered out: " + signal);
                return false;
            }
        }
        
        // Validate signal
        for (SignalValidator validator : validators) {
            ValidationResult result = validator.validate(signal);
            if (!result.isValid()) {
                logger.warning("Signal validation failed: " + result.getMessage() + " - " + signal);
                return false;
            }
        }
        
        // Update recent signals
        addToRecentSignals(signal);
        
        // Dispatch signal to handlers
        for (SignalHandler handler : handlers) {
            try {
                handler.handleSignal(signal);
            } catch (Exception e) {
                logger.severe("Error handling signal in handler: " + e.getMessage());
            }
        }
        
        return true;
    }
    
    /**
     * Sets the maximum number of recent signals to keep.
     * 
     * @param maxRecentSignals The maximum number of recent signals
     */
    public void setMaxRecentSignals(int maxRecentSignals) {
        this.maxRecentSignals = maxRecentSignals;
    }
    
    /**
     * Sets the signal timeout duration.
     * 
     * @param signalTimeout The signal timeout duration
     */
    public void setSignalTimeout(Duration signalTimeout) {
        this.signalTimeout = signalTimeout;
    }
    
    /**
     * Sets the minimum confidence threshold for signals.
     * 
     * @param minimumConfidence The minimum confidence threshold
     */
    public void setMinimumConfidence(BigDecimal minimumConfidence) {
        this.minimumConfidence = minimumConfidence;
    }
    
    /**
     * Gets the recent signals.
     * 
     * @return An unmodifiable list of recent signals
     */
    public List<Signal> getRecentSignals() {
        return Collections.unmodifiableList(recentSignals);
    }
    
    /**
     * Adds a signal to the recent signals list.
     * 
     * @param signal The signal to add
     */
    private void addToRecentSignals(Signal signal) {
        recentSignals.add(signal);
        
        // Trim the list if it exceeds the maximum size
        while (recentSignals.size() > maxRecentSignals) {
            recentSignals.remove(0);
        }
    }
    
    /**
     * Creates and returns a lambda-based signal handler.
     * 
     * @param consumer The signal consumer function
     * @return A signal handler that applies the consumer function
     */
    public static SignalHandler createHandler(Consumer<Signal> consumer) {
        return consumer::accept;
    }
} 