#!/bin/bash
# This script installs the botctl command by creating a symbolic link in a directory in the user's PATH

# Set colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "Forex Trading Bot CLI Installer"
echo "==============================="

# Get the absolute path of the project directory
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOTCTL_SCRIPT="$PROJECT_DIR/src/botctl.py"

# Make sure botctl.py exists and is executable
if [ ! -f "$BOTCTL_SCRIPT" ]; then
    echo -e "${RED}Error: Could not find $BOTCTL_SCRIPT${NC}"
    exit 1
fi

# Make the script executable
chmod +x "$BOTCTL_SCRIPT"
echo -e "${GREEN}✓${NC} Made botctl.py executable"

# Default installation directory
DEFAULT_INSTALL_DIR="/usr/local/bin"

# Ask user for installation directory
read -p "Installation directory [$DEFAULT_INSTALL_DIR]: " INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}

# Check if install directory exists and is in PATH
if [ ! -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR does not exist. Creating it...${NC}"
    sudo mkdir -p "$INSTALL_DIR"
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Failed to create $INSTALL_DIR${NC}"
        exit 1
    fi
fi

# Check if the directory is in the PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR is not in your PATH.${NC}"
    echo "You may need to add it to your PATH manually."
fi

# Create the symbolic link
LINK_PATH="$INSTALL_DIR/botctl"

# Remove existing link if it exists
if [ -L "$LINK_PATH" ] || [ -f "$LINK_PATH" ]; then
    echo "Removing existing botctl link..."
    sudo rm "$LINK_PATH"
fi

# Create the new link
echo "Creating symbolic link to botctl.py in $INSTALL_DIR..."
sudo ln -s "$BOTCTL_SCRIPT" "$LINK_PATH"

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Successfully installed botctl to $LINK_PATH"
    echo
    echo "You can now run the botctl command from anywhere."
    echo "Try running: botctl --help"
else
    echo -e "${RED}Error: Failed to create symbolic link.${NC}"
    exit 1
fi

# Add tab completion for bash if available
if command -v bash &>/dev/null; then
    echo
    echo "Setting up bash tab completion..."
    
    COMPLETION_SCRIPT="$PROJECT_DIR/scripts/bash_completion.d/botctl"
    mkdir -p "$(dirname "$COMPLETION_SCRIPT")"
    
    # Generate completion script using click
    echo "# botctl bash completion script, generated by botctl installer" > "$COMPLETION_SCRIPT"
    echo "_botctl_completion() {" >> "$COMPLETION_SCRIPT"
    echo "    COMPREPLY=( \$( COMP_WORDS=\"\${COMP_WORDS[*]}\" \\" >> "$COMPLETION_SCRIPT"
    echo "                     COMP_CWORD=\$COMP_CWORD \\" >> "$COMPLETION_SCRIPT"
    echo "                     _BOTCTL_COMPLETE=complete \$1 ) )" >> "$COMPLETION_SCRIPT"
    echo "    return 0" >> "$COMPLETION_SCRIPT"
    echo "}" >> "$COMPLETION_SCRIPT"
    echo >> "$COMPLETION_SCRIPT"
    echo "complete -F _botctl_completion -o default botctl" >> "$COMPLETION_SCRIPT"
    
    echo -e "${GREEN}✓${NC} Created bash completion script at $COMPLETION_SCRIPT"
    
    # Check if completion script is already sourced in .bashrc
    if grep -q "source $COMPLETION_SCRIPT" "$HOME/.bashrc" 2>/dev/null; then
        echo "Bash completion already configured in .bashrc"
    else
        echo "# Forex Trading Bot CLI bash completion" >> "$HOME/.bashrc"
        echo "source $COMPLETION_SCRIPT" >> "$HOME/.bashrc"
        echo -e "${GREEN}✓${NC} Added completion script to .bashrc"
        echo "Please restart your terminal or run 'source ~/.bashrc' to enable tab completion"
    fi
fi

echo
echo -e "${GREEN}Installation complete!${NC}"
echo "Run 'botctl --help' to get started." 